"""add merchant_address

Revision ID: 08cf38f2f19a
Revises: bff47eb6fdf2
Create Date: 2025-11-08 22:36:48.723145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08cf38f2f19a'
down_revision: Union[str, None] = 'bff47eb6fdf2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('receipts', sa.Column('merchant_address', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('receipts', 'merchant_address')
    # ### end Alembic commands ###
