"""create receipts schema

Revision ID: bff47eb6fdf2
Revises: 
Create Date: 2025-11-08 22:22:40.393145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

DEFAULT_CATEGORIES = [
    {
        "name": "Potraviny",
        "description": "Bežné nákupy potravín a drogérie",
        "keywords": ["lidl", "tesco", "milk", "chlieb", "potraviny", "coop"],
    },
    {
        "name": "Doprava",
        "description": "PHM, cestovanie, MHD",
        "keywords": ["benz", "shell", "omv", "bus", "vlak", "mhd"],
    },
    {
        "name": "Domácnosť",
        "description": "Domáce potreby, elektro, hobby",
        "keywords": ["ikea", "hornbach", "bau", "obi", "elektro"],
    },
    {
        "name": "Stravovanie",
        "description": "Reštaurácie, kaviarne",
        "keywords": ["kavia", "restaurant", "bistro", "pub", "cafe"],
    },
]


# revision identifiers, used by Alembic.
revision: str = 'bff47eb6fdf2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('receipts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('receipt_id', sa.String(length=128), nullable=False),
    sa.Column('issue_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('merchant_name', sa.String(length=255), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=True),
    sa.Column('source_payload', sa.JSON(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('receipt_id')
    )
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('receipt_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=True),
    sa.Column('total_price', sa.Float(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('suggested_category', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['receipt_id'], ['receipts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pattern', sa.String(length=120), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pattern', name='uq_rule_pattern')
    )
    bind = op.get_bind()
    categories_table = sa.table(
        'categories',
        sa.column('id', sa.Integer),
        sa.column('name', sa.String(length=100)),
        sa.column('description', sa.Text),
    )
    rules_table = sa.table(
        'rules',
        sa.column('id', sa.Integer),
        sa.column('pattern', sa.String(length=120)),
        sa.column('category_id', sa.Integer),
    )
    for category in DEFAULT_CATEGORIES:
        result = bind.execute(
            sa.insert(categories_table)
            .values(name=category['name'], description=category['description'])
            .returning(categories_table.c.id)
        )
        category_id = result.scalar_one()
        keyword_rows = [
            {'pattern': keyword.lower(), 'category_id': category_id}
            for keyword in category.get('keywords', [])
        ]
        if keyword_rows:
            bind.execute(sa.insert(rules_table), keyword_rows)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rules')
    op.drop_table('items')
    op.drop_table('receipts')
    op.drop_table('categories')
    # ### end Alembic commands ###
